### ISSUE TITLE
Use interactive learner table?

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3website#14]
Hey the website looks really great, just wondering if it would make more sense to use one (or both the) interactive learner table instead/as well as the existing lists?

* https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html
* https://mlr3extralearners.mlr-org.com/articles/learners/test_overview.html

**Comment by RaphaelS1** [comment]
Just to add (without adding a new issue), that I found 'Classes' here confusing because it's listed under 'Resources' so seems to imply educational classes

<img width="757" alt="Screenshot 2022-02-27 at 11 09 40" src="https://user-images.githubusercontent.com/25639974/155880015-f0aac801-2978-4f54-968c-7c2d1e800574.png">

**Comment by be-marc** [comment]
> Just to add (without adding a new issue), that I found 'Classes' here confusing because it's listed under 'Resources' so seems to imply educational classes

You are right. The classes are in the navigation bar under "overview" now.

> interactive learner table 

We still use `mlr3extralearners::list_mlr3learners()` to generate the list. I prefer simple tables that fit into the website design. However, if `ctrl + f` is not enough, we can try to style an interactive table like `DT`.

**Comment by be-marc** [comment]
We are using `DT` now.
