### ISSUE TITLE
Error rendering `filter.Rmd`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3website#37]
``` r
library(mlr3filters)

content = as.data.table(mlr_filters, objects = TRUE)[, .(key, label, task_type, packages)]
#> Error in eval(jsub, SDenv, parent.frame()): object 'label' not found
```

<sup>Created on 2022-05-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

https://github.com/mlr-org/mlr3website/blob/main/mlr-org/filters.Rmd#L20

How does this succeed in CI runs?

**Comment by be-marc** [comment]
Should work now.
