### ISSUE TITLE
gallery: 2020-03-18-iris-mlr3-basics fails

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr3website#75]
Line 141 to 145 fails with the current `mlr3extralearners` version. Package `mclust` is not installed. 
I cannot reproduce this when just loading `mlr3extralearners`. 
@sebffischer Can you take a look at this?

**Comment by sebffischer** [comment]
The gallery seems to render: https://github.com/mlr-org/mlr3website/actions/workflows/gallery-weekly.yml 

Can you explain in more detail what the problem is?

**Comment by be-marc** [comment]
Yes, that part is not evaluated at the moment.

https://github.com/mlr-org/mlr3website/blob/105b5fb78b3ab9c4df385d97e2a57c320cce205e/mlr-org/gallery/basic/2020-03-18-iris-mlr3-basics/index.qmd#L140-L145

But let me check again. I had some caching issues.

**Comment by be-marc** [comment]
When activating this part again and calling `quarto render mlr-org/gallery/basic/2020-03-18-iris-mlr3-basics/ --cache-refresh`, I get: 

```
Quitting from lines 141-145 (index.qmd) 
Error in loadNamespace(x) : there is no package called 'mclust'
Calls: .main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

And maybe you have a better idea for the section. Reinstalling the package doesn't seem so smart to me.

**Comment by sebffischer** [comment]
Does this  https://github.com/mlr-org/mlr3website/pull/82/files run for you 

I don't understand why we reinstall at all, loading the library is sufficient to populate the dictionary.

**Comment by sebffischer** [comment]
Wait I have to fix something

**Comment by sebffischer** [comment]
I think this is essentially a bug in mlr3extralearners and mlr3learners etc. 
When unloading a package the items should be removed from the dictionary. If this was correctly implemented a simple `unloadNamespace("mlr3extralearners")` should suffice to show the effect.

**Comment by sebffischer** [comment]
Done
