### ISSUE TITLE
Gallery links are failing

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3website#81]
The links on the main page are failing because of the restructuring. 
Also then clicking on the links under category `latest` in the gallery, they don't do anything.

**Comment by davidbudzynski** [comment]
Thanks for reporting! I'm having the exact same issue as well.

**Comment by davidbudzynski** [comment]
Links to other articles within the "Learn in Bundled Series" are still broken. For example if you go to [German Credit Series](https://mlr-org.com/gallery/series/2020-03-11-basics-german-credit), links to [part II](https://mlr3gallery.mlr-org.com/posts/2020-03-11-mlr3tuning-tutorial-german-credit/) and [part III](https://mlr3gallery.mlr-org.com/posts/2020-03-11-mlr3pipelines-tutorial-german-credit/) are still broken.

**Comment by sebffischer** [comment]
thanks for reporting!

**Comment by davidbudzynski** [comment]
No problem! Btw this also affects [Practical Tuning Series](https://mlr-org.com/gallery/series/2021-03-09-practical-tuning-series-tune-a-support-vector-machine). I had no issue with finding links to these articles if I searched for them by clicking on [see all posts](https://mlr-org.com/gallery-all.html) on the main page though.

**Comment by sebffischer** [comment]
If you want to help, you can also create a PR and fix the links :)

**Comment by davidbudzynski** [comment]
Can do, I will send a PR later 👍

**Comment by be-marc** [comment]
Done

**Comment by davidbudzynski** [comment]
cheers!
