### ISSUE TITLE
Link for book.pdf is broken

### ISSUE THREAD

**Issue by a-alexandre** [mlr-org/mlr3website#87]
### Description

Hi,

On page https://mlr-org.com/book.html the link for the pdf version of the book is broken.

Source here : https://github.com/mlr-org/mlr3website/blob/main/mlr-org/book.qmd#L12

### Reproducible example

https://mlr3book.mlr-org.com/mlr3book.pdf # link broken

**Comment by sebffischer** [comment]
Fixed here: https://github.com/mlr-org/mlr3website/commit/1e68c11f487525a9c5b1179b4e984066f81ea615
